import { NextRequest, NextResponse } from 'next/server'
import { rdbRead, rdbWrite, firmFileName } from '../../../lib/readmedb'

export const runtime = 'nodejs'

export async function POST(req: NextRequest) {
  const { firmName, clients, emailAddress } = await req.json()

  const fileName = firmFileName(firmName)
  const existing = await rdbRead(fileName)

  const clientBlock = `\`\`\`json clients\n${JSON.stringify(clients, null, 2)}\n\`\`\``

  if (!existing) {
    // Brand new firm — create the file
    const content = `# ${firmName} — Recon AI

> This file stores all reconciliation history for **${firmName}**.
> Generated by Recon AI · readmedb.com
> Email: ${emailAddress}

${clientBlock}
`
    await rdbWrite(fileName, content)
  } else if (!existing.includes('```json clients')) {
    // File exists (from a previous recon) but has no client block — prepend it
    await rdbWrite(fileName, clientBlock + '\n\n' + existing)
  } else {
    // File exists with a client block — replace it with updated list (handle CRLF too)
    const updated = existing.replace(/```json clients\r?\n[\s\S]*?\r?\n```/, clientBlock)
    await rdbWrite(fileName, updated)
  }

  return NextResponse.json({ ok: true, file: fileName })
}
