const BASE = 'https://app.readmedb.com/api/v1'
const KEY = process.env.READMEDB_API_KEY!

function headers() {
  return {
    'Authorization': `Bearer ${KEY}`,
    'Content-Type': 'application/json',
  }
}

export function firmFileName(firmName: string): string {
  return `${firmName.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').slice(0, 60)}.md`
}

// ── Core CRUD ────────────────────────────────────────────────────────────────

export async function rdbRead(name: string): Promise<string | null> {
  const res = await fetch(`${BASE}/files/${encodeURIComponent(name)}`, { headers: headers() })
  if (res.status === 404) return null
  if (!res.ok) throw new Error(`ReadmeDB read failed: ${res.status}`)
  const data = await res.json()
  return data.content as string
}

export async function rdbWrite(name: string, content: string): Promise<void> {
  // Try PUT first (overwrite); fall back to POST (create)
  const res = await fetch(`${BASE}/files/${encodeURIComponent(name)}`, {
    method: 'PUT',
    headers: headers(),
    body: JSON.stringify({ content }),
  })
  if (!res.ok) {
    const res2 = await fetch(`${BASE}/files`, {
      method: 'POST',
      headers: headers(),
      body: JSON.stringify({ name, content }),
    })
    if (!res2.ok) throw new Error(`ReadmeDB write failed: ${res2.status} ${await res2.text()}`)
  }
}

export async function rdbAppend(name: string, text: string): Promise<void> {
  const existing = await rdbRead(name)
  await rdbWrite(name, existing ? existing + '\n' + text : text)
}

export async function rdbDelete(name: string): Promise<void> {
  await fetch(`${BASE}/files/${encodeURIComponent(name)}`, { method: 'DELETE', headers: headers() })
}

export async function rdbList(): Promise<Array<{ name: string; updatedAt: string; size: number }>> {
  const res = await fetch(`${BASE}/files`, { headers: headers() })
  if (!res.ok) throw new Error(`ReadmeDB list failed: ${res.status}`)
  const data = await res.json()
  // API returns array of file objects
  return (data.files ?? data ?? []) as Array<{ name: string; updatedAt: string; size: number }>
}

export interface ReconciliationEntry {
  statementFile: string
  date: string
  totalExpected: number
  totalReceived: number
  gap: number
  autoCount: number
  suggestedCount: number
  unmatchedCount: number
  anomalyExplanation: string
  markdownReport: string
}

export async function appendReconciliationToFirm(
  firmName: string,
  entry: ReconciliationEntry,
): Promise<void> {
  const fileName = firmFileName(firmName)
  const existing = await rdbRead(fileName)

  const gapDirection = entry.gap > 0 ? 'shortfall' : entry.gap < 0 ? 'overpaid' : 'balanced'
  const section = `
---

## Reconciliation — ${entry.date}
**Statement:** ${entry.statementFile}

| | Value |
|---|---|
| Expected | £${entry.totalExpected.toFixed(2)} |
| Received | £${entry.totalReceived.toFixed(2)} |
| Gap | £${Math.abs(entry.gap).toFixed(2)} (${gapDirection}) |
| Auto-matched | ${entry.autoCount} |
| Suggested | ${entry.suggestedCount} |
| Unmatched | ${entry.unmatchedCount} |

### Anomaly Analysis
${entry.anomalyExplanation}

<details>
<summary>Full report</summary>

\`\`\`
${entry.markdownReport}
\`\`\`

</details>
`

  let content: string
  if (existing) {
    content = existing + section
  } else {
    content = `# ${firmName} — Recon AI

> This file stores all reconciliation history for **${firmName}**.
> Generated by Recon AI · readmedb.com
${section}`
  }

  await rdbWrite(fileName, content)
}

export async function getFirmFile(firmName: string): Promise<string | null> {
  return rdbRead(firmFileName(firmName))
}
